#pragma once

// WiFi Config
#define WIFI_SSID ""
#define WIFI_PASSWORD ""
#define WIFI_MAX_CONNECTION_RETRY 100


// Button  Config
#define PRIMARY_BUTTON_LEFT_PIN 16
#define PRIMARY_BUTTON_RIGHT_PIN 25
#define PLUNGER_PIN 33
#define BUTTON_DEBOUNCE 50
#define BUTTON_LONG_PRESS 800
#define BUTTON_DOUBLE_CLICK 300