#pragma once

// WiFi Config
#define WIFI_SSID ""
#define WIFI_PASSWORD ""
#define WIFI_MAX_CONNECTION_RETRY 100


// Button  Config
#define PRIMARY_BUTTON_LEFT_PIN 4
#define PRIMARY_BUTTON_RIGHT_PIN 13

#define SECONDARY_BUTTON_LEFT_PIN 16
#define SECONDARY_BUTTON_RIGHT_PIN 25

#define FRONT_PANEL_BUTTON_TOP_PIN 17
#define FRONT_PANEL_BUTTON_MIDDLE_PIN 18
#define FRONT_PANEL_BUTTON_BOTTOM_PIN 19

#define FRONT_PANEL_BUTTON_UNDERPLUNGER_PIN 33 
#define PLUNGER_PIN 32

#define BUTTON_DEBOUNCE 50
#define BUTTON_LONG_PRESS 800
#define BUTTON_DOUBLE_CLICK 300